Spring:
  jpa:
    generate-ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin@1
server:
  port: 8000